/* The same reducer renders live SSE and historical replay. Test failure and ordering semantics. */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {createState,reduceEvent,dagLayout,parseCSV,stepEvidenceHTML,esc}=require('../web/assets/showcase.js');
let s=createState('public demo','live');
let seq=0;
const emit=(type,data={},step=null)=>reduceEvent(s,{seq:++seq,type,data,step,ts_ms:1000+seq*100});
emit('run.started');
emit('retrieval.completed',{selected:['A','B']});
emit('ranking.completed',{top:'B',entries:[{name:'B',priority:.8}]});
emit('orchestration.completed',{skills:['A','B'],order:['A','B'],edges:[['A','B']]});
emit('plan.created',{steps:2});
emit('dag.ready',{nodes:[{idx:0,skill:'A',depends_on:[]},{idx:1,skill:'B',depends_on:[0]}]});
assert.equal(s.phase,4,'dag.ready must not regress the already-created plan');
emit('step.started',{},0);
emit('code.generated',{code:'print(1)'},0);
emit('step.attempt',{attempt:1,ok:false,stderr:'missing file'},0);
emit('step.retry',{reason:'missing file'},0);
emit('step.attempt',{attempt:2,ok:true,stdout:'1'},0);
emit('artifact.created',{name:'a.csv',bytes:20},0);
emit('check.result',{name:'columns',passed:false},0);
const duplicateSeq=seq;
assert.equal(reduceEvent(s,{seq:duplicateSeq,type:'check.result',data:{passed:true},step:0}),false);
assert.equal(s.checks.length,1,'replayed/polled events must not double-count checks');
emit('step.completed',{status:'done',n_attempts:2,checks:'0/1'},0);
emit('steps.skipped',{steps:[1]});
assert.equal(s.nodes[1].status,'skipped');
assert.equal(s.nodes[0].attempt,2);
emit('execution.finished',{done:1,failed:0});
emit('judge.completed',{weighted:null,score_valid:false,reward:null});
emit('evolution.proposed',{accepted:false,skipped:true,feedback:[{nudged:false}]});
emit('run.finished',{status:'PARTIAL',duration_ms:9000});
assert.equal(s.finished,true);
assert.equal(s.status,'PARTIAL');
assert.equal(s.checks.filter(c=>c.passed).length,0);
assert.equal(s.judge.weighted,null,'unavailable evaluation must not turn into a zero or a passing result');
assert.equal(s.evolution.accepted,false);
s=createState('cancel','live');seq=0;emit('run.started');emit('run.cancelled',{reason:'user cancelled'});emit('run.finished',{status:'CANCELLED'});
assert.equal(s.phases[0],'failed');
assert.ok(s.phases.slice(1).every(p=>p==='pending'),'unfinished phases must not be presented as completed');
const nodes=[{idx:0,depends_on:[]},{idx:1,depends_on:[0]},{idx:2,depends_on:[0]},{idx:3,depends_on:[1,2]}];
for(const narrow of [false,true]){const l=dagLayout(nodes,narrow);for(const p of l.points.values()){assert.ok(p.x>=0&&p.y>=0);assert.ok(p.x+p.w<=l.width&&p.y+p.h<=l.height);}const boxes=[...l.points.values()];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert.ok(a.x+a.w<=b.x||b.x+b.w<=a.x||a.y+a.h<=b.y||b.y+b.h<=a.y,'sibling DAG nodes must not overlap on mobile or desktop');}}
assert.equal(dagLayout([{idx:0,depends_on:[1]},{idx:1,depends_on:[0]}]).points.size,2);
assert.deepEqual(parseCSV('a,b\r\n"<script>","quoted,cell"\r\n"two\nlines","a""b"\n'),[['a','b'],['<script>','quoted,cell'],['two\nlines','a"b']]);
assert.equal(esc('<img onerror="evil">'),'&lt;img onerror=&quot;evil&quot;&gt;');
const html=fs.readFileSync(path.join(__dirname,'../web/briefing.html'),'utf8');
assert.ok(html.indexOf('id="s3"')<html.indexOf('id="s1"'),'real question stage must precede explanatory sections');
for(const hook of ['Showcase.start(q, history)','Showcase.created(run_id)','Showcase.event(ev)','Showcase.finish(fin)','Showcase.fail(e.message || e)'])assert.ok(html.includes(hook),hook);
assert.equal((html.match(/id="task"/g)||[]).length,1,'one input must drive one request');
assert.equal((html.match(/id="demo-seven"/g)||[]).length,1);
assert.equal((html.match(/class="tl-item" data-s="[1-7]"/g)||[]).length,7);
const publicRun=JSON.parse(fs.readFileSync(path.join(__dirname,'../out/runs/690f6144-20261007-232529-0368.json'),'utf8'));
s=createState(publicRun.task,'replay');publicRun.events.forEach(e=>reduceEvent(s,e));
assert.equal(s.status,publicRun.status);
assert.equal(s.nodes.filter(n=>n.status==='done').length,publicRun.step_stats.done);
assert.equal(s.checks.length,publicRun.steps.flatMap(n=>n.checks).length);
assert.equal(s.artifacts.length,publicRun.artifacts.length);
const latestRun=JSON.parse(fs.readFileSync(path.join(__dirname,'../out/runs/7356cc57-20261008-012151-3b64.json'),'utf8'));
s=createState(latestRun.task,'replay');latestRun.events.forEach(e=>reduceEvent(s,e));
assert.equal(s.status,'COMPLETED');
assert.equal(s.nodes.filter(n=>n.status==='done').length,3);
assert.equal(s.checks.filter(c=>c.passed).length,27);
assert.equal(s.artifacts.length,4);
assert.equal(s.evolution.skipped,true,'semantic failures must remain visible and prevent learning');
assert.equal(latestRun.staged.learning_gate.eligible,false);
assert.equal(s.feedback.filter(f=>f.nudged).length,0);
const candidateState=createState('candidate gate');
reduceEvent(candidateState,{seq:1,type:'evolution.proposed',data:{accepted:false,candidate:{state:'pending_frozen_evaluation'}}});
assert.equal(candidateState.evolution.accepted,false);
assert.ok(candidateState.logs.at(-1).text.includes('候选区'));
const followup=JSON.parse(fs.readFileSync(path.join(__dirname,'../out/runs/02f80093-20261008-175420-f527.json'),'utf8'));
const detail=stepEvidenceHTML(followup.steps[0]);
assert.match(detail,/必要检查 10\/10/);
assert.match(detail,/CSV 原值投影与排序/);
assert.match(detail,new RegExp(followup.steps[0].input_artifacts[0].sha256));
assert.ok(detail.indexOf('CSV 原值投影与排序')<detail.indexOf('查看实际执行代码'));
assert.doesNotMatch(stepEvidenceHTML({action:'<script>',checks:[{name:'<img>',detail:'<iframe>'}]}),/<script>|<img>|<iframe>/);
for(const a of latestRun.artifacts){
  const bytes=fs.readFileSync(path.join(__dirname,'../out/runs',latestRun.run_id,'artifacts',a.name));
  assert.equal(require('node:crypto').createHash('sha256').update(bytes).digest('hex'),a.sha256,'shipped replay artifact must match actual registered content');
}
console.log('Executive stage: actual record replay, event deduplication, phase order, partial/cancelled runs, repair, DAG layouts and safe CSV preview passed.');
